### ISSUE TITLE
using this to render a cuboid per entity?

### ISSUE THREAD

**Issue by laundmo** [ForesightMiningSoftwareCorporation/bevy_aabb_instancing#1]
For static scenes made from cuboids this seems perfect, but im quite confused whether this can be used to efficiently render a lot of cuboids on bevy entities which might move or be changed.

Currently it's unclear whether thats even a possibility, or how to do it if it is. As far as i can see, i would have to update the entity containing the Cuboids component from all the entities i want to render as cuboids.

Ideally some more examples would be very nice, especially ones showing the cuboids moving in any way (if this is supported).

**Comment by bonsairobo** [comment]
It's most efficient to cluster instances into a small number of buffers. Think of it this way: when a mesh is rendered, there are many triangles stored in a single component. It's exactly the same here: a `Cuboids` component is like a `Mesh` in that it stores many (cuboid) primitives in one buffer/component.

So your question about rendering multiple moving cuboids is like asking how to render many moving triangles in a `Mesh` (except that the cuboids renderer does not support skinning).

So the answer is you need to collect your individual cuboid entities (if you need them to be entities) into a single `Cuboids` component for rendering. If the cuboids are moving then you need to do this every frame.

**Comment by laundmo** [comment]
Thank you, that clears up the intended way yo use this a lot. I think i was expecting that this crate would provide a system which automatically gathers entities with a cuboid component into a cuboids for me, but knowing that it doesn't, writing my own should be quite easy.

Would you consider adding a example with a system like this? would allow others to find this out easily.
